before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
      - darwin_amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: Brandon Wagner
    
    description: |-
      a diskstats formatter for humans
    
    license: MIT
    
    formats:
      - deb
      - rpm
brews:
  -
    tap:
      owner: bwagner5
      name: homebrew-wagner
    caveats: "cat /proc/diskstats | dsfmt"
    homepage: "https://github.com/bwagner5/dsfmt"
    description: "diskstats formatter for humans"
    license: "MIT"
    test: |
      system "#{bin}/dsfmt --help"
dockers:
  -
    image_templates:
    - "ghcr.io/bwagner5/dsfmt:latest"
    - "ghcr.io/bwagner5/dsfmt:{{ .Tag }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/bwagner5/dsfmt"
